"""empty message

Revision ID: 2d89a47e453c
Revises: None
Create Date: 2016-03-04 10:05:49.869585

"""

# revision identifiers, used by Alembic.
revision = '2d89a47e453c'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
