"""empty message

Revision ID: 3f70fae034e7
Revises: None
Create Date: 2016-03-04 10:19:41.873382

"""

# revision identifiers, used by Alembic.
revision = '3f70fae034e7'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('genre', sa.String(length=64), nullable=True),
    sa.Column('review', sa.String(length=255), nullable=True),
    sa.Column('director', sa.String(length=64), nullable=True),
    sa.Column('release_year', sa.Integer(), nullable=True),
    sa.Column('availability', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_movies_director', 'movies', ['director'], unique=False)
    op.create_index('ix_movies_genre', 'movies', ['genre'], unique=False)
    op.create_index('ix_movies_title', 'movies', ['title'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('last_update', sa.DateTime(), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_users_email', 'users', ['email'], unique=True)
    op.create_index('ix_users_is_admin', 'users', ['is_admin'], unique=False)
    op.create_index('ix_users_username', 'users', ['username'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_username', 'users')
    op.drop_index('ix_users_is_admin', 'users')
    op.drop_index('ix_users_email', 'users')
    op.drop_table('users')
    op.drop_index('ix_movies_title', 'movies')
    op.drop_index('ix_movies_genre', 'movies')
    op.drop_index('ix_movies_director', 'movies')
    op.drop_table('movies')
    ### end Alembic commands ###
