"""empty message

Revision ID: b6502bfc3ad8
Revises: None
Create Date: 2016-02-20 16:59:36.484307

"""

# revision identifiers, used by Alembic.
revision = 'b6502bfc3ad8'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie', sa.Column('availability', sa.Integer(), nullable=False))
    op.add_column('movie', sa.Column('director', sa.String(), nullable=True))
    op.add_column('movie', sa.Column('genre', sa.String(), nullable=True))
    op.add_column('movie', sa.Column('releaseYear', sa.Integer(), nullable=True))
    op.add_column('movie', sa.Column('title', sa.String(), nullable=False))
    op.drop_column('movie', 'file_name')
    op.drop_column('movie', 'price')
    op.drop_column('movie', 'version')
    op.drop_column('movie', 'is_active')
    op.drop_column('movie', 'name')
    op.drop_column('users', 'password')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.VARCHAR(length=255), nullable=False))
    op.add_column('movie', sa.Column('name', sa.VARCHAR(), nullable=True))
    op.add_column('movie', sa.Column('is_active', sa.BOOLEAN(), nullable=True))
    op.add_column('movie', sa.Column('version', sa.VARCHAR(), nullable=True))
    op.add_column('movie', sa.Column('price', sa.FLOAT(), nullable=True))
    op.add_column('movie', sa.Column('file_name', sa.VARCHAR(), nullable=True))
    op.drop_column('movie', 'title')
    op.drop_column('movie', 'releaseYear')
    op.drop_column('movie', 'genre')
    op.drop_column('movie', 'director')
    op.drop_column('movie', 'availability')
    ### end Alembic commands ###
